services:
  db:
    image: "postgres:14"
    restart: on-failure
    shm_size: 128mb
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    restart: on-failure
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db-data:
