services:
  db:
    image: "postgres:14"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ./temp/postgresql/data:/var/lib/postgresql/data

  adminer:
    restart: always
    image: adminer
    ports:
      - "8080:8080"
