services:
  db:
    image: "postgres:14"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
