# Generated by Django 5.0.2 on 2024-03-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteCustomization",
            fields=[
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="sites.site",
                        verbose_name="site",
                    ),
                ),
                (
                    "is_open_for_signup",
                    models.BooleanField(
                        default=False, verbose_name="is open for signup"
                    ),
                ),
            ],
            options={
                "verbose_name": "site customization",
                "verbose_name_plural": "site customizations",
                "ordering": ["site"],
            },
        ),
    ]
