# Generated by Django 5.0.3 on 2024-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecustomization",
            name="api_theme",
            field=models.CharField(
                choices=[
                    ("default", "default"),
                    ("cerulean", "cerulean"),
                    ("cosmo", "cosmo"),
                    ("cyborg", "cyborg"),
                    ("darkly", "darkly"),
                    ("flatly", "flatly"),
                    ("journal", "journal"),
                    ("lumen", "lumen"),
                    ("paper", "paper"),
                    ("readable", "readable"),
                    ("sandstone", "sandstone"),
                    ("simplex", "simplex"),
                    ("slate", "slate"),
                    ("spacelab", "spacelab"),
                    ("superhero", "superhero"),
                    ("united", "united"),
                    ("yeti", "yeti"),
                ],
                default="default",
                max_length=16,
                verbose_name="API Bootstrap theme",
            ),
        ),
    ]
