name: bandit

on:
  pull_request:

jobs:
  bandit:
    name: "Search for common security issues in Python code"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install bandit[toml]

      - name: Run bandit
        run: |
          bandit \
            --verbose \
            --recursive \
            --configfile pyproject.toml \
            apps \
            manage.py \
            templates \
            tests \
            toolbox
