name: Check code quality

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:14"
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Create a virtual environment
        run: python -m venv venv
      - name: Install test dependencies
        run: |
          venv/bin/python -m pip install \
            --requirement requirements.txt \
            --requirement requirements-test.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        env:
          POSTGRES_HOST: postgres
        with:
          extra_args: --all-files
