name: pytest

on:
  pull_request:

jobs:
  pytest:
    name: "Run unit tests"
    runs-on: self-hosted

    services:
      postgres:
        image: "postgres:14"
        env:
          POSTGRES_DB: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create a virtual environment
        run: python -m venv venv

      - name: Install dependencies
        run: |
          venv/bin/python -m pip install \
            --requirement requirements.txt \
            --requirement requirements-test.txt

      - name: Run pytest
        env:
          DJANGO_SETTINGS_MODULE: toolbox.settings
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          venv/bin/pytest
